---
abstract: 'simple image uploading to your own server'
author:
  - 'Thomas Thurman <thomas@thurman.org.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Gehazi
no_index:
  directory:
    - inc
    - share
    - t
requires:
  File::ShareDir: 0
  File::Slurp: 0
  perl: 5.005
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
