.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH IMGUR 1 "January 2011" Linux "User Manuals"
.SH NAME
imgur \- upload images to the web
.SH SYNOPSIS
.B imgur [-b]
.I filename
.br
.B imgur -l
.br
.B imgur -r [-b]
.I record_name
.SH DESCRIPTION
.B imgur
uploads images to imgur.com, and optionally
launches the system web browser to view the
uploaded image.
It can also list any previously
uploaded images, and re-display their
details.
No account or payment is needed to host images
on imgur.com, and therefore this program should
operate correctly with no configuration.

Details of each image are printed to standard
output in three tab-delimited columns. The
first column is an identifier for the image.
The second is a field name, and the third is a value.
This allows you to use
.B grep(1)
and
.B cut(1)
to pull out only the parts you need.
A list of valid field names is given in
.B KEYS
, below.
.SH OPTIONS
.IP -b
Launch the browser to look at the uploaded image.
This may be combined with the
.B -r
option, to allow you to look at a previously-uploaded
image in the browser.
.IP -l
List all previously uploaded images to standard output.
The images are listed newest first.
Their identifiers may be in the form of filenames; if so,
they represent thumbnails of the images, and only the
part without the path or extension is significant.
If there are no previously uploaded files, prints
"(no records to list)" to standard error.
.IP -r
View the records of a previously-uploaded image.
Identifiers are case-sensitive.
The identifier may be given in plain form, such as
.I LThFy
, or in the form of a filename, such as
.I /home/user/.local/share/imgur/LThFy.jpg
-- if given as a filename, the path and extension
are discarded.
You can obtain a list of valid identifiers using the
.B -l
option.
.SH KEYS
These are the strings you may find in the second column
of the results tables which are printed to standard output.
.IP delete_hash
A secret value used by the API to allow deletion of the
copy of the image on the web. Not currently usable by
this program, though it will be later.
.IP delete_page
The address of a web page which includes the
.I delete_hash
mentioned above. This allows you to delete the copy
of the image on the web using a web browser.
.IP filename
The original name of the file on your computer which was
uploaded.

This field is inserted by the program locally; it is
not generated by the remote server. As such, it is not
printed after an upload, only as part of a historical record.
.IP image_hash
A six-character identifier which represents the copy of
the image on the web. This is the simplest form which
may be used to refer to the image. It is case-sensitive.
.IP imgur_page
The address of a web page where you may view the image.
This address is what the
.B -b
option opens in the web browser.
.IP large_thumbnail
The web address of a large thumbnail of the image,
suitable for inclusion in blogs.  This image is generally
at most 640 pixels on its longest side.
.IP local_thumbnail
A local copy of the image referenced by
.I small_thumbnail
whose filename can also be used as a reference
to the image as a whole. This is the filename
which the
.B -l
option attempts to use in its listings.

This field is inserted by the program locally; it is
not generated by the remote server. As such, it is not
printed after an upload, only as part of a historical record.
.IP original_image
The web address for a copy of the original image,
at the same size.
.IP small_thumbnail
The web address of a small thumbnail of the image.
This image is generally at most 100 pixels on its longest side.
.IP time
The time at which the upload was made. This is stored
as a number of seconds since the epoch, but printed
as a human-readable date. The date format is sortable.

This field is inserted by the program locally; it is
not generated by the remote server. As such, it is not
printed after an upload, only as part of a historical record.
.SH DIAGNOSTICS
The following diagnostics may be issued on standard error:
 
(no records to list)
.RS
You requested a listing of previous uploads,
but there are none to list. Either you have never
uploaded files using this program, or the program
has been told not to log uploads.
.RE
(name) found 0
.RS
You asked to list the details of a record which
was not found.
.SH FILES
These paths are derived from the specifications given
in the XDG Base Directory Specification, and so may
vary according to the provisions of that document.
.IP /etc/xdg/imgur/imgur.conf
Site-wide configuration file, in key-file format.
Currently ignored: this is a bug.
The file is well-commented;
copy it to the path given in the
next entry to customise it for yourself.
.IP ~/.config/imgur/imgur.conf
Local configuration, in the same format
as the preceding entry.
In particular, you may set the
.I recording
key in the
.I general
group to 0 to prevent recording of uploads.
.IP ~/.local/share/imgur/uploads.conf
The details of previous uploads.
Thumbnails of these uploads are stored in the
same directory.
.SH BUGS
See
.I https://github.com/tthurman/imgur-integration/issues
for an up-to-date list of issues.

See
.I https://github.com/tthurman/imgur-integration/wiki/roadmap
to get an idea about priorities for fixing them.

Patches and suggestions are always welcome.
.SH AUTHOR
Thomas Thurman <thomas@thurman.org.uk>
.SH SEE ALSO
Further documentation may be found at
.I https://github.com/tthurman/imgur-integration/wiki
